/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author jjaac
 */
public class HomeScreen extends javax.swing.JFrame
{

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen()
    {
        initComponents();
        setLocation(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        data_Input_Type = new javax.swing.JTextField();
        live_Data_Button = new javax.swing.JButton();
        user_Data_Button = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Strategy Home Screen");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        data_Input_Type.setEditable(false);
        data_Input_Type.setText("Do you want to use live F1 data or your own data?");
        data_Input_Type.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                data_Input_TypeActionPerformed(evt);
            }
        });
        getContentPane().add(data_Input_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, -1, 49));

        live_Data_Button.setText("F1Live Data");
        live_Data_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                live_Data_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(live_Data_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 190, 130));

        user_Data_Button.setText("Personal Data");
        user_Data_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                user_Data_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(user_Data_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(846, 585, 210, 130));

        backgroundLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jcj\\Documents\\NetBeansProjects\\PAT\\EOY_PAT\\src\\main\\resources\\images\\F1Lights1.png")); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void data_Input_TypeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_data_Input_TypeActionPerformed
    {//GEN-HEADEREND:event_data_Input_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_Input_TypeActionPerformed

    private void live_Data_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_live_Data_ButtonActionPerformed
    {//GEN-HEADEREND:event_live_Data_ButtonActionPerformed
        // TODO add your handling code here:
        F1Login loginS = new F1Login();
        loginS.setVisible(true);
        dispose();
    }//GEN-LAST:event_live_Data_ButtonActionPerformed

    private void user_Data_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_user_Data_ButtonActionPerformed
    {//GEN-HEADEREND:event_user_Data_ButtonActionPerformed
        // TODO add your handling code here:
        User_Tyre_InputScreen uIS = new User_Tyre_InputScreen();
        uIS.setVisible(true);
        dispose();
    }//GEN-LAST:event_user_Data_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JTextField data_Input_Type;
    private javax.swing.JButton live_Data_Button;
    private javax.swing.JButton user_Data_Button;
    // End of variables declaration//GEN-END:variables
}
