/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author jjaac
 */
public class HomeScreen extends javax.swing.JFrame
{

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen()
    {
        initComponents();
        setLocation(590, 360);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        data_Input_Type = new javax.swing.JTextField();
        live_Data_Button = new javax.swing.JButton();
        user_Data_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Strategy Home Screen");

        data_Input_Type.setEditable(false);
        data_Input_Type.setText("Do you want to use live F1 data or your own data?");
        data_Input_Type.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                data_Input_TypeActionPerformed(evt);
            }
        });

        live_Data_Button.setText("F1Live Data");
        live_Data_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                live_Data_ButtonActionPerformed(evt);
            }
        });

        user_Data_Button.setText("Personal Data");
        user_Data_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                user_Data_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(live_Data_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(user_Data_Button))
                    .addComponent(data_Input_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(data_Input_Type, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(live_Data_Button)
                    .addComponent(user_Data_Button))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void data_Input_TypeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_data_Input_TypeActionPerformed
    {//GEN-HEADEREND:event_data_Input_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_Input_TypeActionPerformed

    private void live_Data_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_live_Data_ButtonActionPerformed
    {//GEN-HEADEREND:event_live_Data_ButtonActionPerformed
        // TODO add your handling code here:
        F1Login loginS = new F1Login();
        loginS.setVisible(true);
        dispose();
    }//GEN-LAST:event_live_Data_ButtonActionPerformed

    private void user_Data_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_user_Data_ButtonActionPerformed
    {//GEN-HEADEREND:event_user_Data_ButtonActionPerformed
        // TODO add your handling code here:
        User_Tyre_InputScreen uIS = new User_Tyre_InputScreen();
        uIS.setVisible(true);
        dispose();
    }//GEN-LAST:event_user_Data_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField data_Input_Type;
    private javax.swing.JButton live_Data_Button;
    private javax.swing.JButton user_Data_Button;
    // End of variables declaration//GEN-END:variables
}
