/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Backend.Strategy;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jjaac
 */
public class User_Tyre_InputScreen extends javax.swing.JFrame
{

    /**
     * Creates new form User_Data_Screen
     */
    public User_Tyre_InputScreen()
    {
        initComponents();
        setLocation(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        soft_Tyres_Label = new javax.swing.JLabel();
        soft_First_Lap_Time_label = new javax.swing.JLabel();
        soft_Last_Lap_Time_label = new javax.swing.JLabel();
        soft_Max_Laps_label = new javax.swing.JLabel();
        soft_FirstLapTimeField = new javax.swing.JTextField();
        soft_LastLapTimeField = new javax.swing.JTextField();
        soft_MaxLapsField = new javax.swing.JTextField();
        calculate_Button = new javax.swing.JButton();
        back_Button = new javax.swing.JButton();
        medium_LastLapSecondsField = new javax.swing.JTextField();
        medium_FirstLapSecondsField = new javax.swing.JTextField();
        medium_MaxLapsField = new javax.swing.JTextField();
        hard_FirstLapTimeField = new javax.swing.JTextField();
        hard_LastLapTimeField = new javax.swing.JTextField();
        hard_MaxLapsField = new javax.swing.JTextField();
        medium_Tyres_Label = new javax.swing.JLabel();
        hard_Tyres_Label = new javax.swing.JLabel();
        output_Field = new javax.swing.JScrollPane();
        output_TextArea = new javax.swing.JTextArea();
        raceDistance_Label = new javax.swing.JLabel();
        raceDistance_Field = new javax.swing.JTextField();
        pitTime_Label = new javax.swing.JLabel();
        pitTime_Field = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\jjaac\\Pictures\\Screenshots\\F1Lights2 (2).PNG")); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Data Input Screen");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setText("Please type in the according information for the following fields:");
        jTextField1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 401, 31));

        soft_Tyres_Label.setForeground(new java.awt.Color(33, 33, 33));
        soft_Tyres_Label.setText("Soft Tyres:");
        getContentPane().add(soft_Tyres_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, -1, -1));

        soft_First_Lap_Time_label.setForeground(new java.awt.Color(33, 33, 33));
        soft_First_Lap_Time_label.setText("First Lap-Time of stint (seconds): ");
        getContentPane().add(soft_First_Lap_Time_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        soft_Last_Lap_Time_label.setForeground(new java.awt.Color(33, 33, 33));
        soft_Last_Lap_Time_label.setText("Last Lap-Time of stint (seconds):");
        getContentPane().add(soft_Last_Lap_Time_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 170, -1));

        soft_Max_Laps_label.setForeground(new java.awt.Color(33, 33, 33));
        soft_Max_Laps_label.setText("Maximum amount of laps on tyre:");
        getContentPane().add(soft_Max_Laps_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, -1));

        soft_FirstLapTimeField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                soft_FirstLapTimeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(soft_FirstLapTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 55, -1));
        getContentPane().add(soft_LastLapTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 600, 55, -1));
        getContentPane().add(soft_MaxLapsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 630, 55, -1));

        calculate_Button.setText("Calculate");
        calculate_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                calculate_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(calculate_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 770, -1, -1));

        back_Button.setText("Back");
        back_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                back_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(back_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 770, 73, -1));
        getContentPane().add(medium_LastLapSecondsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, 55, -1));

        medium_FirstLapSecondsField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                medium_FirstLapSecondsFieldActionPerformed(evt);
            }
        });
        getContentPane().add(medium_FirstLapSecondsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 55, -1));
        getContentPane().add(medium_MaxLapsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 630, 55, -1));

        hard_FirstLapTimeField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                hard_FirstLapTimeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(hard_FirstLapTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, 55, -1));
        getContentPane().add(hard_LastLapTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 600, 55, -1));

        hard_MaxLapsField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                hard_MaxLapsFieldActionPerformed(evt);
            }
        });
        getContentPane().add(hard_MaxLapsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 55, -1));

        medium_Tyres_Label.setForeground(new java.awt.Color(33, 33, 33));
        medium_Tyres_Label.setText("Medium Tyres:");
        getContentPane().add(medium_Tyres_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, -1, -1));

        hard_Tyres_Label.setForeground(new java.awt.Color(33, 33, 33));
        hard_Tyres_Label.setText("Hard Tyres:");
        getContentPane().add(hard_Tyres_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, -1, -1));

        output_TextArea.setColumns(20);
        output_TextArea.setRows(5);
        output_Field.setViewportView(output_TextArea);

        getContentPane().add(output_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 495, 292));

        raceDistance_Label.setForeground(new java.awt.Color(33, 33, 33));
        raceDistance_Label.setText("How many laps does the race consist of?");
        getContentPane().add(raceDistance_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 733, -1));
        getContentPane().add(raceDistance_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, 690, -1));

        pitTime_Label.setForeground(new java.awt.Color(33, 33, 33));
        pitTime_Label.setText("Average pit-lane time?");
        getContentPane().add(pitTime_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 733, -1));
        getContentPane().add(pitTime_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 740, 690, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\jjaac\\Pictures\\Screenshots\\F1Lights2 (2).PNG")); // NOI18N
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -120, 1360, 1070));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soft_FirstLapTimeFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_soft_FirstLapTimeFieldActionPerformed
    {//GEN-HEADEREND:event_soft_FirstLapTimeFieldActionPerformed
        // TODO add your handling code here:
    	
    }//GEN-LAST:event_soft_FirstLapTimeFieldActionPerformed

    private void hard_FirstLapTimeFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_hard_FirstLapTimeFieldActionPerformed
    {//GEN-HEADEREND:event_hard_FirstLapTimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard_FirstLapTimeFieldActionPerformed

    private void hard_MaxLapsFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_hard_MaxLapsFieldActionPerformed
    {//GEN-HEADEREND:event_hard_MaxLapsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard_MaxLapsFieldActionPerformed

    private void medium_FirstLapSecondsFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_medium_FirstLapSecondsFieldActionPerformed
    {//GEN-HEADEREND:event_medium_FirstLapSecondsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medium_FirstLapSecondsFieldActionPerformed

    private void back_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_back_ButtonActionPerformed
    {//GEN-HEADEREND:event_back_ButtonActionPerformed
        // TODO add your handling code here:
        new HomeScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_back_ButtonActionPerformed

    private void calculate_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_calculate_ButtonActionPerformed
    {//GEN-HEADEREND:event_calculate_ButtonActionPerformed
        PrintWriter info = null;
        try {
            // TODO add your handling code here:
            info = new PrintWriter("info.txt");
            //format: slap1#mlap1#hlap1#lastLap#maxLaps
            info.print(soft_FirstLapTimeField.getText() +"#"+ medium_FirstLapSecondsField.getText() +"#"+ hard_FirstLapTimeField.getText() +"#"+ soft_LastLapTimeField.getText() +"#"+ medium_LastLapSecondsField.getText() +"#"+ hard_LastLapTimeField.getText() +"#"+ soft_MaxLapsField.getText() +"#"+ medium_MaxLapsField.getText() +"#"+ hard_MaxLapsField.getText() +"#"+ raceDistance_Field.getText());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(User_Tyre_InputScreen.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            info.close();
        }
//        double sLap1 = Double.parseDouble(soft_FirstLapTimeField.getText() );
//        double mLap1 = Double.parseDouble(medium_FirstLapSecondsField.getText() );
//        double hLap1 = Double.parseDouble(hard_FirstLapTimeField.getText() );
//        double sLastLap = Double.parseDouble(soft_LastLapTimeField.getText() );
//        double mLastLap = Double.parseDouble(medium_LastLapSecondsField.getText());
//        double hLastLap = Double.parseDouble(hard_LastLapTimeField.getText());
//        int sMaxLaps = Integer.parseInt(soft_MaxLapsField.getText() );
//        int mMaxLaps = Integer.parseInt(medium_MaxLapsField.getText());
//        int hMaxLaps = Integer.parseInt(hard_MaxLapsField.getText());
//        int raceDist = Integer.parseInt(raceDistance_Field.getText());
        
        output_TextArea.setText(Strategy.getStrats());
    }//GEN-LAST:event_calculate_ButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed
    {//GEN-HEADEREND:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_Button;
    private javax.swing.JButton calculate_Button;
    private javax.swing.JTextField hard_FirstLapTimeField;
    private javax.swing.JTextField hard_LastLapTimeField;
    private javax.swing.JTextField hard_MaxLapsField;
    private javax.swing.JLabel hard_Tyres_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField medium_FirstLapSecondsField;
    private javax.swing.JTextField medium_LastLapSecondsField;
    private javax.swing.JTextField medium_MaxLapsField;
    private javax.swing.JLabel medium_Tyres_Label;
    private javax.swing.JScrollPane output_Field;
    private javax.swing.JTextArea output_TextArea;
    private javax.swing.JTextField pitTime_Field;
    private javax.swing.JLabel pitTime_Label;
    private javax.swing.JTextField raceDistance_Field;
    private javax.swing.JLabel raceDistance_Label;
    private javax.swing.JTextField soft_FirstLapTimeField;
    private javax.swing.JLabel soft_First_Lap_Time_label;
    private javax.swing.JTextField soft_LastLapTimeField;
    private javax.swing.JLabel soft_Last_Lap_Time_label;
    private javax.swing.JTextField soft_MaxLapsField;
    private javax.swing.JLabel soft_Max_Laps_label;
    private javax.swing.JLabel soft_Tyres_Label;
    // End of variables declaration//GEN-END:variables
}