/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Backend.UserManager;
import javax.swing.JOptionPane;

/**
 *
 * @author janch
 */
public class AddUserScreen extends javax.swing.JFrame {

    /**
     * Creates new form AddUserScreen
     */
    public AddUserScreen() {
        initComponents();
        setLocationRelativeTo(null);
        currentUsers_TextArea.setText
        (UserManager.getUsers()
        );
    }
    //Initialize variables:
    private String username, password;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        currentUsers_TextArea = new javax.swing.JTextArea();
        currUsers_Label = new javax.swing.JLabel();
        confirmPassword_Label = new javax.swing.JLabel();
        confirmPasskey_Field = new javax.swing.JPasswordField();
        username_Field = new javax.swing.JTextField();
        username_Label = new javax.swing.JLabel();
        userPassword_Label = new javax.swing.JLabel();
        userPassword_Field = new javax.swing.JTextField();
        addUser_Button = new javax.swing.JButton();
        back_Button = new javax.swing.JButton();
        home_Button = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1290, 1080));
        setMinimumSize(new java.awt.Dimension(1290, 1080));
        setPreferredSize(new java.awt.Dimension(1290, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        currentUsers_TextArea.setEditable(false);
        currentUsers_TextArea.setColumns(20);
        currentUsers_TextArea.setRows(5);
        jScrollPane1.setViewportView(currentUsers_TextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 260, 150));

        currUsers_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        currUsers_Label.setForeground(new java.awt.Color(68, 68, 68));
        currUsers_Label.setText("Users:");
        getContentPane().add(currUsers_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, 80, -1));

        confirmPassword_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        confirmPassword_Label.setForeground(new java.awt.Color(68, 68, 68));
        confirmPassword_Label.setText("Confirm Your Password:");
        getContentPane().add(confirmPassword_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, -1, -1));
        getContentPane().add(confirmPasskey_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 700, 260, -1));
        getContentPane().add(username_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 260, -1));

        username_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        username_Label.setForeground(new java.awt.Color(68, 68, 68));
        username_Label.setText("Enter Your Username:");
        getContentPane().add(username_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        userPassword_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        userPassword_Label.setForeground(new java.awt.Color(68, 68, 68));
        userPassword_Label.setText("Enter Your Password:");
        getContentPane().add(userPassword_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, -1));

        userPassword_Field.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                userPassword_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(userPassword_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 260, -1));

        addUser_Button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        addUser_Button.setText("ADD USER");
        addUser_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addUser_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addUser_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 750, -1, -1));

        back_Button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        back_Button.setText("BACK");
        back_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                back_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(back_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 750, -1, -1));

        home_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/F1Logo.png"))); // NOI18N
        home_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                home_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(home_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 30));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/F1Lights3.png"))); // NOI18N
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-245, 0, 1035, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userPassword_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPassword_FieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userPassword_FieldActionPerformed

    private void back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_ButtonActionPerformed
        // TODO add your handling code here:
        new UserLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_back_ButtonActionPerformed

    private void addUser_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUser_ButtonActionPerformed
        // TODO add your handling code here:
        char [] arr = confirmPasskey_Field.getPassword();
        
        //essentially a .toString method
        String confirmPassword = "";
        for (int i = 0; i < arr.length; i++) 
        {
           confirmPassword += arr[i];
        }
        password = userPassword_Field.getText();
        username = username_Field.getText();
        if (  !(username.isBlank() && !password.isBlank()) && !confirmPassword.isBlank())
        {
            UserManager.addUser(username, password, confirmPassword);
//            new PathChoice().setVisible(true);
//            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please fill in all of the cells.");
        }
        currentUsers_TextArea.setText
        (UserManager.getUsers()
        );
    }//GEN-LAST:event_addUser_ButtonActionPerformed

    private void home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_ButtonActionPerformed
        // TODO add your handling code here:
        new HomeScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_home_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUser_Button;
    private javax.swing.JButton back_Button;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JPasswordField confirmPasskey_Field;
    private javax.swing.JLabel confirmPassword_Label;
    private javax.swing.JLabel currUsers_Label;
    private javax.swing.JTextArea currentUsers_TextArea;
    private javax.swing.JButton home_Button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField userPassword_Field;
    private javax.swing.JLabel userPassword_Label;
    private javax.swing.JTextField username_Field;
    private javax.swing.JLabel username_Label;
    // End of variables declaration//GEN-END:variables
}
