/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Backend.UserManager;

/**
 *
 * @author janch
 */
public class AddUserScreen extends javax.swing.JFrame {

    /**
     * Creates new form AddUserScreen
     */
    public AddUserScreen() {
        initComponents();
        setLocationRelativeTo(null);
        currentUsers_TextArea.setText
        (UserManager.getUsers()
        );
    }
    //Initialize variables:
    private String username, password;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        currentUsers_TextArea = new javax.swing.JTextArea();
        currUsers_Label = new javax.swing.JLabel();
        confirmPassword_Label = new javax.swing.JLabel();
        confirmPasskey_Field = new javax.swing.JTextField();
        username_Field = new javax.swing.JTextField();
        username_Label = new javax.swing.JLabel();
        userPassword_Label = new javax.swing.JLabel();
        userPassword_Field = new javax.swing.JTextField();
        addUser_Button = new javax.swing.JButton();
        back_Button = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        currentUsers_TextArea.setColumns(20);
        currentUsers_TextArea.setRows(5);
        jScrollPane1.setViewportView(currentUsers_TextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 260, 150));

        currUsers_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        currUsers_Label.setForeground(new java.awt.Color(68, 68, 68));
        currUsers_Label.setText("Users:");
        getContentPane().add(currUsers_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, 80, -1));

        confirmPassword_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        confirmPassword_Label.setForeground(new java.awt.Color(68, 68, 68));
        confirmPassword_Label.setText("Confirm Your Password:");
        getContentPane().add(confirmPassword_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, -1, -1));

        confirmPasskey_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasskey_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(confirmPasskey_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 700, 260, -1));
        getContentPane().add(username_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 260, -1));

        username_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        username_Label.setForeground(new java.awt.Color(68, 68, 68));
        username_Label.setText("Enter Your Username:");
        getContentPane().add(username_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        userPassword_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        userPassword_Label.setForeground(new java.awt.Color(68, 68, 68));
        userPassword_Label.setText("Enter Your Password:");
        getContentPane().add(userPassword_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, -1));

        userPassword_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPassword_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(userPassword_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 260, -1));

        addUser_Button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        addUser_Button.setText("ADD USER");
        addUser_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUser_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addUser_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 770, -1, -1));

        back_Button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        back_Button.setText("BACK");
        back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(back_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 770, -1, -1));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/F1Lights4.png"))); // NOI18N
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, 0, 1010, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmPasskey_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasskey_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasskey_FieldActionPerformed

    private void userPassword_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPassword_FieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userPassword_FieldActionPerformed

    private void back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_ButtonActionPerformed
        // TODO add your handling code here:
        new UserLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_back_ButtonActionPerformed

    private void addUser_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUser_ButtonActionPerformed
        // TODO add your handling code here:
        password = userPassword_Field.getText();
        username = username_Field.getText();
        if (  !(username == null && password == null) )
        {
            UserManager.addUser(username, password);
        }
        currentUsers_TextArea.setText
        (UserManager.getUsers()
        );
    }//GEN-LAST:event_addUser_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUser_Button;
    private javax.swing.JButton back_Button;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JTextField confirmPasskey_Field;
    private javax.swing.JLabel confirmPassword_Label;
    private javax.swing.JLabel currUsers_Label;
    private javax.swing.JTextArea currentUsers_TextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField userPassword_Field;
    private javax.swing.JLabel userPassword_Label;
    private javax.swing.JTextField username_Field;
    private javax.swing.JLabel username_Label;
    // End of variables declaration//GEN-END:variables
}
