/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Backend.TeacherManager;

/**
 *
 * @author janch
 */
public class ClientInput extends javax.swing.JFrame
{
    boolean [][] timeTable;
    /**
     * Creates new form ClientInput
     */
    public ClientInput()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        makeTT_Button = new javax.swing.JButton();
        addTeacher_Button = new javax.swing.JButton();
        addname_Button = new javax.swing.JButton();
        name_Label = new javax.swing.JLabel();
        name_Field = new javax.swing.JTextField();
        battings_Spinner = new javax.swing.JSpinner();
        battings_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        makeTT_Button.setText("make timetable");
        makeTT_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                makeTT_ButtonActionPerformed(evt);
            }
        });

        addTeacher_Button.setText("add teacher");
        addTeacher_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addTeacher_ButtonActionPerformed(evt);
            }
        });

        addname_Button.setText("Add name");

        name_Label.setText("Name: ");

        battings_Label.setText("Battings");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(makeTT_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addname_Button)
                .addGap(43, 43, 43)
                .addComponent(addTeacher_Button)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_Label)
                    .addComponent(battings_Label, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(battings_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_Label)
                    .addComponent(name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(battings_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(battings_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTeacher_Button)
                    .addComponent(addname_Button)
                    .addComponent(makeTT_Button))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void makeTT_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_makeTT_ButtonActionPerformed
    {//GEN-HEADEREND:event_makeTT_ButtonActionPerformed
        // TODO add your handling code here:
        timeTable = new boolean [][]
        {
            {true, true, false, false, false, false, true, true, false, false, false, true, true, true},
            {true, true, true, true, false, false, false, false, true, true, false, true, true, false},
            {true, true, true, true, true, false, true, true, true, true, false, true, true, true},
            {true, true, false, true, true, false, false, false, true, true, false, true, true, true},
            {true, true, true, true, true, true, false, true, false, false, false}
        };
    }//GEN-LAST:event_makeTT_ButtonActionPerformed

    private void addTeacher_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addTeacher_ButtonActionPerformed
    {//GEN-HEADEREND:event_addTeacher_ButtonActionPerformed
        // TODO add your handling code here:
        TeacherManager tm = new TeacherManager();
        tm.addTeacher(name_Field.getText(), timeTable, (int) battings_Spinner.getValue());
    }//GEN-LAST:event_addTeacher_ButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ClientInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ClientInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ClientInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ClientInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ClientInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTeacher_Button;
    private javax.swing.JButton addname_Button;
    private javax.swing.JLabel battings_Label;
    private javax.swing.JSpinner battings_Spinner;
    private javax.swing.JButton makeTT_Button;
    private javax.swing.JTextField name_Field;
    private javax.swing.JLabel name_Label;
    // End of variables declaration//GEN-END:variables
}
