/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Backend.BattingLesson;
import Backend.BattingManager;
import Backend.Teacher;
import Backend.TeacherManager;
import com.formdev.flatlaf.ui.FlatComboBoxUI;
import javax.swing.JButton;
import javax.swing.DefaultComboBoxModel;
import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.event.ChangeListener;
/**
 *
 * @author janch
 */
public final class EditBattingsFrame extends javax.swing.JFrame
{
    private int dayOfMonth, lesson;
    private String[] teacherNames;
    private ArrayList <BattingLesson> battingLessons;
    /**
     * Creates new form EditBattingFrame
     */
    public EditBattingsFrame(ArrayList<BattingLesson> battingLessons)
    {
        
        this.dayOfMonth = battingLessons.get(0).getDayOfMonth();
        this.lesson = battingLessons.get(0).getLesson();
        this.battingLessons = battingLessons;
        teacherNames = new String[battingLessons.size()];
        int i = 0;
        for(BattingLesson bl: battingLessons)
        {
            teacherNames[i] = bl.getFullName();
            i++;
        }
        
        initComponents();
        dayOfMonthSpinner.getModel().setValue(dayOfMonth);
        dayOfMonthSpinner.setValue(battingLessons.get(0).getDayOfMonth());
        lessonSpinner.setValue(battingLessons.get(0).getLesson());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        panelHeaderLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        teacherComboBox = new javax.swing.JComboBox<>();
        lessonSpinner = new javax.swing.JSpinner();
        dayOfMonthSpinner = new javax.swing.JSpinner();
        dayofWeekLabel = new javax.swing.JLabel();
        confirmEditsButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        deleteBattingButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        panelHeaderLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        panelHeaderLabel.setForeground(new java.awt.Color(51, 51, 51));
        panelHeaderLabel.setText("Change the Batting Information");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lesson:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Teacher:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Day of Month:");

        teacherComboBox.setBackground(new java.awt.Color(204, 255, 204));
        teacherComboBox.setEditable(true);
        teacherComboBox.setUI(new FlatComboBoxUI(){         @Override             protected JButton createArrowButton() {                 //---style arrow button anyway you like                 
            JButton arrowButton = new JButton();                 
            arrowButton.setBorder(null);                 
            arrowButton.setBorderPainted(false);                
            arrowButton.setText("v");                 
            arrowButton.setBackground(new java.awt.Color(0,102,0));                 return arrowButton;              
        }     
    }); //get values 
    teacherComboBox.setModel(new DefaultComboBoxModel<String> (teacherNames));
    teacherComboBox.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            teacherComboBoxActionPerformed(evt);
        }
    });

    lessonSpinner.setBackground(new java.awt.Color(204,255,204));
    lessonSpinner.getComponent(0).setBackground(new java.awt.Color(0,102,0));
    lessonSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 14, 1));

    dayOfMonthSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
    dayOfMonthSpinner.setBackground(new java.awt.Color(204,255,204));
    dayOfMonthSpinner.getComponent(0).setBackground(new java.awt.Color(0,102,0));

    dayofWeekLabel.setForeground(new java.awt.Color(0, 102, 51));

    confirmEditsButton.setBackground(new java.awt.Color(0, 153, 51));
    confirmEditsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    confirmEditsButton.setForeground(new java.awt.Color(204, 255, 255));
    confirmEditsButton.setText("Confirm changes");
    confirmEditsButton.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            confirmEditsButtonActionPerformed(evt);
        }
    });

    closeButton.setBackground(new java.awt.Color(204, 255, 204));
    closeButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    closeButton.setForeground(new java.awt.Color(153, 153, 153));
    closeButton.setText("X");
    closeButton.setBorder(null);
    closeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
        public void mouseMoved(java.awt.event.MouseEvent evt)
        {
            closeButtonMouseMoved(evt);
        }
    });
    closeButton.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            closeButtonActionPerformed(evt);
        }
    });

    deleteBattingButton.setBackground(new java.awt.Color(153, 0, 0));
    deleteBattingButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    deleteBattingButton.setForeground(new java.awt.Color(204, 255, 204));
    deleteBattingButton.setText("Delete Batting");
    deleteBattingButton.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            deleteBattingButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jSeparator1)
                    .addContainerGap())
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(dayofWeekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lessonSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(teacherComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dayOfMonthSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28))))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(94, 94, 94)
            .addComponent(panelHeaderLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
            .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(confirmEditsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteBattingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(teacherComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(lessonSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dayOfMonthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(dayofWeekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(confirmEditsButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(deleteBattingButton)
            .addGap(10, 10, 10))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButtonActionPerformed
    {//GEN-HEADEREND:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void closeButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_closeButtonMouseMoved
    {//GEN-HEADEREND:event_closeButtonMouseMoved
        // TODO add your handling code here:
        closeButton.setBackground(Color.red);
    }//GEN-LAST:event_closeButtonMouseMoved

    private void teacherComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_teacherComboBoxActionPerformed
    {//GEN-HEADEREND:event_teacherComboBoxActionPerformed
        // TODO add your handling code here:
        BattingLesson lessonInFocus = battingLessons.get(teacherComboBox.getSelectedIndex());
        dayOfMonthSpinner.setValue(lessonInFocus.getDayOfMonth());
        lessonSpinner.setValue(lessonInFocus.getLesson());
        
    }//GEN-LAST:event_teacherComboBoxActionPerformed

    private void confirmEditsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_confirmEditsButtonActionPerformed
    {//GEN-HEADEREND:event_confirmEditsButtonActionPerformed
        // TODO add your handling code here:
        BattingLesson updatedLesson = battingLessons.get(teacherComboBox.getSelectedIndex());
        BattingLesson originalLesson = battingLessons.get(teacherComboBox.getSelectedIndex());
        updatedLesson.setBattingDay((int) dayOfMonthSpinner.getValue());
        updatedLesson.setLesson((int) lessonSpinner.getValue());
        
        BattingManager bm = new BattingManager();
        TeacherManager tm = new TeacherManager(); 
        try
        {
            Teacher t = tm.getTeacher(updatedLesson.getFullName());
            if(tm.isFree(t, updatedLesson.getLesson(), ((updatedLesson.getDayOfMonth()-1)/7+1) ,updatedLesson.getDayOfMonth(), updatedLesson.getMonth(), updatedLesson.getYear())) 
            {
                battingLessons.set(teacherComboBox.getSelectedIndex(),updatedLesson);
                dayOfMonthSpinner.setValue(updatedLesson.getDayOfMonth());
                lessonSpinner.setValue(updatedLesson.getLesson());
                
                bm.addBatting(updatedLesson);
                bm.deleteBatting(originalLesson);
                dispose();
            }
            else {
                JOptionPane.showMessageDialog(this, "Lesson already occupied for this teacher, choose another.");
            }
        } catch (SQLException ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_confirmEditsButtonActionPerformed

    private void deleteBattingButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deleteBattingButtonActionPerformed
    {//GEN-HEADEREND:event_deleteBattingButtonActionPerformed
        // TODO add your handling code here:
        BattingManager bm = new BattingManager();
        try
        {
            bm.deleteBatting(battingLessons.get(teacherComboBox.getSelectedIndex()));
            dispose();
        } catch (SQLException ex)
        {
            Logger.getLogger(EditBattingsFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteBattingButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(EditBattingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(EditBattingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(EditBattingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(EditBattingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton confirmEditsButton;
    private javax.swing.JSpinner dayOfMonthSpinner;
    private javax.swing.JLabel dayofWeekLabel;
    private javax.swing.JButton deleteBattingButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner lessonSpinner;
    private javax.swing.JLabel panelHeaderLabel;
    private javax.swing.JComboBox<String> teacherComboBox;
    // End of variables declaration//GEN-END:variables
}
