/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Jcj
 */
public class PathChoice extends javax.swing.JFrame
{

    /**
     * Creates new form PathChoice
     */
    public PathChoice()
    {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        addStrat_Button = new javax.swing.JButton();
        userStrats_Button = new javax.swing.JButton();
        background_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 33, 33));
        jLabel1.setText("Would you like to view your current strategies or calculate a new one?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 600, 40));

        addStrat_Button.setText("Add Strategy");
        addStrat_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addStrat_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addStrat_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 680, 120, 100));

        userStrats_Button.setText("My Strategies");
        userStrats_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                userStrats_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(userStrats_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 690, 120, 100));

        background_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/F1Lights3.png"))); // NOI18N
        getContentPane().add(background_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, 0, 1040, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userStrats_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_userStrats_ButtonActionPerformed
    {//GEN-HEADEREND:event_userStrats_ButtonActionPerformed
        // TODO add your handling code here:
        new UserStrategies().setVisible(true);
        dispose();
    }//GEN-LAST:event_userStrats_ButtonActionPerformed

    private void addStrat_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addStrat_ButtonActionPerformed
    {//GEN-HEADEREND:event_addStrat_ButtonActionPerformed
        // TODO add your handling code here:
        new User_Tyre_InputScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_addStrat_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStrat_Button;
    private javax.swing.JLabel background_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton userStrats_Button;
    // End of variables declaration//GEN-END:variables
}
