/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BackendTesting;

/**
 *
 * @author janch
 */
public class JTableCalendars extends javax.swing.JFrame
{

    /**
     * Creates new form JTableCalendars
     */
    public JTableCalendars()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabJan = new javax.swing.JPanel();
        jScrollPane20 = new javax.swing.JScrollPane();
        tblJanuary = new javax.swing.JTable();
        tabFeb = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        tblFebruary = new javax.swing.JTable();
        tabMarch = new javax.swing.JPanel();
        jScrollPane18 = new javax.swing.JScrollPane();
        tblMarch = new javax.swing.JTable();
        tabApril = new javax.swing.JPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        tblApril = new javax.swing.JTable();
        tabMay = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        tblMay = new javax.swing.JTable();
        tabJune = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        tblJune = new javax.swing.JTable();
        tabJuly = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        tblJuly = new javax.swing.JTable();
        tabAug = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        tblAugust = new javax.swing.JTable();
        tabSept = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        tblSeptember = new javax.swing.JTable();
        tabOct = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblOctober = new javax.swing.JTable();
        tabNov = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblNovember = new javax.swing.JTable();
        tabDec = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblDecember = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblJanuary.setBackground(new java.awt.Color(255, 255, 255));
        tblJanuary.setForeground(new java.awt.Color(153, 153, 153));
        tblJanuary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"1", "2", "3", "4", "5", "6", "7"},
                {"8", "9", "10", "11", "12", "13", "14"},
                {"15", "16", "17", "18", "19", "20", "21"},
                {"22", "23", "24", "25", "26", "27", "28"},
                {"29", "30", null, null, null, null, null}
            },
            new String []
            {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblJanuary.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblJanuary.setGridColor(new java.awt.Color(102, 102, 102));
        tblJanuary.setRowHeight(100);
        tblJanuary.getTableHeader().setReorderingAllowed(false);
        jScrollPane20.setViewportView(tblJanuary);

        javax.swing.GroupLayout tabJanLayout = new javax.swing.GroupLayout(tabJan);
        tabJan.setLayout(tabJanLayout);
        tabJanLayout.setHorizontalGroup(
            tabJanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane20, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        tabJanLayout.setVerticalGroup(
            tabJanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane20, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("January", tabJan);

        tblFebruary.setBackground(new java.awt.Color(255, 255, 255));
        tblFebruary.setForeground(new java.awt.Color(153, 153, 153));
        tblFebruary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"1", "2", "3", "4", "5", "6", "7"},
                {"8", "9", "10", "11", "12", "13", "14"},
                {"15", "16", "17", "18", "19", "20", "21"},
                {"22", "23", "24", "25", "26", "27", "28"},
                {"29", "30", null, null, null, null, null}
            },
            new String []
            {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblFebruary.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblFebruary.setGridColor(new java.awt.Color(102, 102, 102));
        tblFebruary.setRowHeight(100);
        tblFebruary.getTableHeader().setReorderingAllowed(false);
        jScrollPane19.setViewportView(tblFebruary);

        javax.swing.GroupLayout tabFebLayout = new javax.swing.GroupLayout(tabFeb);
        tabFeb.setLayout(tabFebLayout);
        tabFebLayout.setHorizontalGroup(
            tabFebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        tabFebLayout.setVerticalGroup(
            tabFebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("February", tabFeb);

        tblMarch.setBackground(new java.awt.Color(255, 255, 255));
        tblMarch.setForeground(new java.awt.Color(153, 153, 153));
        tblMarch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"1", "2", "3", "4", "5", "6", "7"},
                {"8", "9", "10", "11", "12", "13", "14"},
                {"15", "16", "17", "18", "19", "20", "21"},
                {"22", "23", "24", "25", "26", "27", "28"},
                {"29", "30", null, null, null, null, null}
            },
            new String []
            {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblMarch.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblMarch.setGridColor(new java.awt.Color(102, 102, 102));
        tblMarch.setRowHeight(100);
        tblMarch.getTableHeader().setReorderingAllowed(false);
        jScrollPane18.setViewportView(tblMarch);

        javax.swing.GroupLayout tabMarchLayout = new javax.swing.GroupLayout(tabMarch);
        tabMarch.setLayout(tabMarchLayout);
        tabMarchLayout.setHorizontalGroup(
            tabMarchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        tabMarchLayout.setVerticalGroup(
            tabMarchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("March", tabMarch);

        tblApril.setBackground(new java.awt.Color(255, 255, 255));
        tblApril.setForeground(new java.awt.Color(153, 153, 153));
        tblApril.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"1", "2", "3", "4", "5", "6", "7"},
                {"8", "9", "10", "11", "12", "13", "14"},
                {"15", "16", "17", "18", "19", "20", "21"},
                {"22", "23", "24", "25", "26", "27", "28"},
                {"29", "30", null, null, null, null, null}
            },
            new String []
            {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblApril.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblApril.setGridColor(new java.awt.Color(102, 102, 102));
        tblApril.setRowHeight(100);
        tblApril.getTableHeader().setReorderingAllowed(false);
        jScrollPane17.setViewportView(tblApril);

        javax.swing.GroupLayout tabAprilLayout = new javax.swing.GroupLayout(tabApril);
        tabApril.setLayout(tabAprilLayout);
        tabAprilLayout.setHorizontalGroup(
            tabAprilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane17, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        tabAprilLayout.setVerticalGroup(
            tabAprilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane17, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("April", tabApril);

        tblMay.setBackground(new java.awt.Color(255, 255, 255));
        tblMay.setForeground(new java.awt.Color(153, 153, 153));
        tblMay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"1", "2", "3", "4", "5", "6", "7"},
                {"8", "9", "10", "11", "12", "13", "14"},
                {"15", "16", "17", "18", "19", "20", "21"},
                {"22", "23", "24", "25", "26", "27", "28"},
                {"29", "30", null, null, null, null, null}
            },
            new String []
            {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblMay.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblMay.setGridColor(new java.awt.Color(102, 102, 102));
        tblMay.setRowHeight(100);
        tblMay.getTableHeader().setReorderingAllowed(false);
        jScrollPane16.setViewportView(tblMay);

        javax.swing.GroupLayout tabMayLayout = new javax.swing.GroupLayout(tabMay);
        tabMay.setLayout(tabMayLayout);
        tabMayLayout.setHorizontalGroup(
            tabMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        tabMayLayout.setVerticalGroup(
            tabMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("May", tabMay);

        tblJune.setBackground(new java.awt.Color(255, 255, 255));
        tblJune.setForeground(new java.awt.Color(153, 153, 153));
        tblJune.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"1", "2", "3", "4", "5", "6", "7"},
                {"8", "9", "10", "11", "12", "13", "14"},
                {"15", "16", "17", "18", "19", "20", "21"},
                {"22", "23", "24", "25", "26", "27", "28"},
                {"29", "30", null, null, null, null, null}
            },
            new String []
            {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblJune.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblJune.setGridColor(new java.awt.Color(102, 102, 102));
        tblJune.setRowHeight(100);
        tblJune.getTableHeader().setReorderingAllowed(false);
        jScrollPane15.setViewportView(tblJune);

        javax.swing.GroupLayout tabJuneLayout = new javax.swing.GroupLayout(tabJune);
        tabJune.setLayout(tabJuneLayout);
        tabJuneLayout.setHorizontalGroup(
            tabJuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        tabJuneLayout.setVerticalGroup(
            tabJuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("June", tabJune);

        tblJuly.setBackground(new java.awt.Color(255, 255, 255));
        tblJuly.setForeground(new java.awt.Color(153, 153, 153));
        tblJuly.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"1", "2", "3", "4", "5", "6", "7"},
                {"8", "9", "10", "11", "12", "13", "14"},
                {"15", "16", "17", "18", "19", "20", "21"},
                {"22", "23", "24", "25", "26", "27", "28"},
                {"29", "30", null, null, null, null, null}
            },
            new String []
            {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblJuly.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblJuly.setGridColor(new java.awt.Color(102, 102, 102));
        tblJuly.setRowHeight(100);
        tblJuly.getTableHeader().setReorderingAllowed(false);
        jScrollPane14.setViewportView(tblJuly);

        javax.swing.GroupLayout tabJulyLayout = new javax.swing.GroupLayout(tabJuly);
        tabJuly.setLayout(tabJulyLayout);
        tabJulyLayout.setHorizontalGroup(
            tabJulyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        tabJulyLayout.setVerticalGroup(
            tabJulyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("July", tabJuly);

        tblAugust.setBackground(new java.awt.Color(255, 255, 255));
        tblAugust.setForeground(new java.awt.Color(153, 153, 153));
        tblAugust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"1", "2", "3", "4", "5", "6", "7"},
                {"8", "9", "10", "11", "12", "13", "14"},
                {"15", "16", "17", "18", "19", "20", "21"},
                {"22", "23", "24", "25", "26", "27", "28"},
                {"29", "30", null, null, null, null, null}
            },
            new String []
            {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblAugust.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblAugust.setGridColor(new java.awt.Color(102, 102, 102));
        tblAugust.setRowHeight(100);
        tblAugust.getTableHeader().setReorderingAllowed(false);
        jScrollPane13.setViewportView(tblAugust);

        javax.swing.GroupLayout tabAugLayout = new javax.swing.GroupLayout(tabAug);
        tabAug.setLayout(tabAugLayout);
        tabAugLayout.setHorizontalGroup(
            tabAugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        tabAugLayout.setVerticalGroup(
            tabAugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("August", tabAug);

        tblSeptember.setBackground(new java.awt.Color(255, 255, 255));
        tblSeptember.setForeground(new java.awt.Color(153, 153, 153));
        tblSeptember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"1", "2", "3", "4", "5", "6", "7"},
                {"8", "9", "10", "11", "12", "13", "14"},
                {"15", "16", "17", "18", "19", "20", "21"},
                {"22", "23", "24", "25", "26", "27", "28"},
                {"29", "30", null, null, null, null, null}
            },
            new String []
            {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblSeptember.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblSeptember.setGridColor(new java.awt.Color(102, 102, 102));
        tblSeptember.setRowHeight(100);
        tblSeptember.getTableHeader().setReorderingAllowed(false);
        jScrollPane12.setViewportView(tblSeptember);

        javax.swing.GroupLayout tabSeptLayout = new javax.swing.GroupLayout(tabSept);
        tabSept.setLayout(tabSeptLayout);
        tabSeptLayout.setHorizontalGroup(
            tabSeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        tabSeptLayout.setVerticalGroup(
            tabSeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("September", tabSept);

        tblOctober.setBackground(new java.awt.Color(255, 255, 255));
        tblOctober.setForeground(new java.awt.Color(153, 153, 153));
        tblOctober.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"1", "2", "3", "4", "5", "6", "7"},
                {"8", "9", "10", "11", "12", "13", "14"},
                {"15", "16", "17", "18", "19", "20", "21"},
                {"22", "23", "24", "25", "26", "27", "28"},
                {"29", "30", null, null, null, null, null}
            },
            new String []
            {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblOctober.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblOctober.setGridColor(new java.awt.Color(102, 102, 102));
        tblOctober.setRowHeight(100);
        tblOctober.getTableHeader().setReorderingAllowed(false);
        jScrollPane11.setViewportView(tblOctober);

        javax.swing.GroupLayout tabOctLayout = new javax.swing.GroupLayout(tabOct);
        tabOct.setLayout(tabOctLayout);
        tabOctLayout.setHorizontalGroup(
            tabOctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        tabOctLayout.setVerticalGroup(
            tabOctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("October", tabOct);

        tblNovember.setBackground(new java.awt.Color(255, 255, 255));
        tblNovember.setForeground(new java.awt.Color(153, 153, 153));
        tblNovember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"1", "2", "3", "4", "5", "6", "7"},
                {"8", "9", "10", "11", "12", "13", "14"},
                {"15", "16", "17", "18", "19", "20", "21"},
                {"22", "23", "24", "25", "26", "27", "28"},
                {"29", "30", null, null, null, null, null}
            },
            new String []
            {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblNovember.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblNovember.setGridColor(new java.awt.Color(102, 102, 102));
        tblNovember.setRowHeight(100);
        tblNovember.getTableHeader().setReorderingAllowed(false);
        jScrollPane10.setViewportView(tblNovember);

        javax.swing.GroupLayout tabNovLayout = new javax.swing.GroupLayout(tabNov);
        tabNov.setLayout(tabNovLayout);
        tabNovLayout.setHorizontalGroup(
            tabNovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        tabNovLayout.setVerticalGroup(
            tabNovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("November", tabNov);

        tblDecember.setBackground(new java.awt.Color(255, 255, 255));
        tblDecember.setForeground(new java.awt.Color(153, 153, 153));
        tblDecember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"1", "2", "3", "4", "5", "6", "7"},
                {"8", "9", "10", "11", "12", "13", "14"},
                {"15", "16", "17", "18", "19", "20", "21"},
                {"22", "23", "24", "25", "26", "27", "28"},
                {"29", "30", null, null, null, null, null}
            },
            new String []
            {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblDecember.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblDecember.setGridColor(new java.awt.Color(102, 102, 102));
        tblDecember.setRowHeight(100);
        tblDecember.getTableHeader().setReorderingAllowed(false);
        jScrollPane9.setViewportView(tblDecember);

        javax.swing.GroupLayout tabDecLayout = new javax.swing.GroupLayout(tabDec);
        tabDec.setLayout(tabDecLayout);
        tabDecLayout.setHorizontalGroup(
            tabDecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        tabDecLayout.setVerticalGroup(
            tabDecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("December", tabDec);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JTableCalendars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JTableCalendars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JTableCalendars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JTableCalendars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new JTableCalendars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel tabApril;
    private javax.swing.JPanel tabAug;
    private javax.swing.JPanel tabDec;
    private javax.swing.JPanel tabFeb;
    private javax.swing.JPanel tabJan;
    private javax.swing.JPanel tabJuly;
    private javax.swing.JPanel tabJune;
    private javax.swing.JPanel tabMarch;
    private javax.swing.JPanel tabMay;
    private javax.swing.JPanel tabNov;
    private javax.swing.JPanel tabOct;
    private javax.swing.JPanel tabSept;
    private javax.swing.JTable tblApril;
    private javax.swing.JTable tblAugust;
    private javax.swing.JTable tblDecember;
    private javax.swing.JTable tblFebruary;
    private javax.swing.JTable tblJanuary;
    private javax.swing.JTable tblJuly;
    private javax.swing.JTable tblJune;
    private javax.swing.JTable tblMarch;
    private javax.swing.JTable tblMay;
    private javax.swing.JTable tblNovember;
    private javax.swing.JTable tblOctober;
    private javax.swing.JTable tblSeptember;
    // End of variables declaration//GEN-END:variables
}
